### ISSUE TITLE
The printed circuit recipes not working in the advanced rocketry cutting machine

### ISSUE THREAD

**Issue by Gabisan2** [ThePansmith/Enigmatica2ExpertUnofficialSkyblock#15]
**Modpack version**
1.3.8.2

**Issue**
The printed circuit recipes dont work in the advanced rocketry cutting machine

Expected result
I put in 1 block of diamond/1 block of gold/ 9 pure certus quartz I get 9 printed engineering circuits/9 printed logic circuits/ 9 printed calculation circuits
Actual result
I put the items in the input and they just stay there with nothing happening

**Comment by Tassadaritze** [comment]
This seems to be because of an empty recipe that constantly runs if the cutting machine is on:
![](https://media.discordapp.net/attachments/1054493416655945832/1155970862621655151/image.png)
It appears that this happens because of invalid recipes in config/advRocketry/CuttingMachine.xml
Commenting out the recipes for Twilight Forest and Biomes O' Plenty wood types fixed the issue for me.
