### ISSUE TITLE
the artstyle looks horrendeus

### ISSUE THREAD

**Issue by HazardEST** [ThePansmith/Enigmatica2ExpertUnofficialSkyblock#4]
sorry dont wanna be that guy but the loading screen looks like some old windows bluescreen and the spinning thing has pixelated outlines that look bad

and the menu background images could be in a higher resolution / less blurry

i'm not a digital artist myself but i feel it cant be too hard to make it a tad bit better looking, probably attracting more players to play aswell

looking forward to play the skyblock version with my friend :)

**Comment by ThePansmith** [comment]
Vaporeon issue was something ive been meaning to tackle, and has been fixed in [e8e6904](https://github.com/ThePansmith/Enigmatica2ExpertUnofficialSkyblock/commit/e8e6904906bec9c8a24e6a6a37f5ef5b3fc382a6). Turns out Forge hates transparent pixels :trollface:. 

As for the base pics, those come from E2E, I'm looking to do a screenshot contest to replace em for e2eu(s). I have no plans on changing the loading screen colors, but if you can not stand it, the colors can be changed in the splash.properties file on your instance.
